---
- name: Configure Nextcloud
  hosts: 127.0.0.1 moleculeTest
  gather_facts: false
  connection: local
  remote_user: "{{user_var}}"

  vars_files:
    - ../user_group_vars/vault.yml
    - ../local_or_remote.yml
    - ../user_group_vars/usernames.yml

  vars:
    ########### Config for the /home/vagrant/nextcloud/.env file
    # MySQL credentials
    mysql_db: mysql_db
    mysql_user: mysql_user
    mysql_password: "{{ vault_mysql_password_nextcloud }}"
    mysql_host: mysql_host
    # Admin
    nextcloud_admin_user: "{{ username_nextcloud_admin_user }}"
    nextloud_admin_password: "{{ vault_nextcloud_admin_password_nextcloud }}"
    # Persistent data directory on the host
    # It is NORMAL that it is vagrant here
    nextcloud_data_dir: /home/vagrant/nextcloud/data
    nextcloud_trusted_domains: 127.0.0.1 nextcloud.micropole.com 10.10.13.12
    # SMTP credentials : this link is very useful to understand the config:
    # https://github.com/nextcloud/docker/issues/1187
    smtp_host: mail.gmx.com
    smtp_secure: tls  # Set to ssl to use SSL, or tls to use STARTTLS.
    smtp_port: 587
    # (default: LOGIN): The method used for authentication.
    # Use PLAIN if no authentication is required.
    smtp_authtype: LOGIN
    smtp_name: Ild8NMJXewJewfZ7@gmx.fr
    smtp_password: "{{ vault_smtp_password_dockerfile }}"
    # Set the local-part for the 'from' field in the emails sent by Nextcloud.
    mail_from_address: Ild8NMJXewJewfZ7
    # Set a different domain for the emails than the nextcloud domain.
    mail_domain: gmx.fr

    # Accessibility
    nextcloud_port: 80
    IP: 127.0.0.1
    ###########

  tasks:
    - include_tasks: /janus/services/templates/nextcloud/nextcloud.yml
