---
#######################################
- name: Create backup directory
  become: true
  file:
    path: /opt/mattermost_backup
    state: directory
    mode: "0777"
#######################################
# This script do a backup of the DB every day at 00:00 and keep max 7 backups
- name: Import backup db script
  template:
    src: ../../../services/backupScript/mattermost/export_db.sh.j2
    dest: /opt/mattermost_backup/export_db.sh
    mode: "0777"
#######################################
# This script import the initial db
- name: Import db script
  template:
    src: ../../../services/backupScript/mattermost/import_db.sh
    dest: /opt/mattermost_backup/import_db.sh
    mode: "0777"
#######################################
- name: Config CRON job to save mattermost db
  become: true
  cron:
    name: "mattermost_db_backup"
    minute: "0"
    hour: "0"
    user: "vagrant"
    job: "/opt/mattermost_backup/export_db.sh"
    cron_file: mattermost_db_backup
    state: present
#######################################
- name: Import backup.sql
  copy:
    src: "{{path_backup_secure}}"
    dest: /opt/mattermost_backup/backup.sql
    mode: "0777"
#######################################
- name: Execute shell command
  become: true
  ansible.builtin.shell: ./import_db.sh
  args:
    chdir: /opt/mattermost_backup/
