---
########################################
- name: Create directory for mattermost files
  file:
    path: /home/{{user_var}}/mattermost
    state: directory
  tags:
    - dir_mattermost
########################################
- name: Clone the Mattermost docker repository
  git:
    repo: https://github.com/mattermost/docker
    dest: /home/{{user_var}}/mattermost
    clone: true
    update: true
  register: git_clone_result
  tags:
    - clone_mattermost_repository
########################################
- name: Copy the 'env.example' file to 'env' file
  copy:
    src: /home/{{user_var}}/mattermost/env.example
    dest: /home/{{user_var}}/mattermost/.env
    remote_src: true
  tags:
    - copy_env_file
########################################
- name: Modify the 'DOMAIN=' line in the '.env' file
  lineinfile:
    path: /home/{{user_var}}/mattermost/.env
    regexp: '^DOMAIN='
    line: 'DOMAIN=localhost:{{PORT}}'
  tags:
    - modify_domain_line
########################################
- name: Create subdirectories
  ansible.builtin.shell: "mkdir -p ./volumes/app/mattermost/{{ item }}"
  loop:
    - config
    - data
    - logs
    - plugins
    - client/plugins
    - bleve-indexes
  args:
    chdir: /home/{{user_var}}/mattermost/
#######################################
- name: Import Mattermost SMTP Config
  become: true
  copy:
    src: backup/config.json
    dest: >-
      /home/{{user_var}}/mattermost/volumes/app/mattermost/config/config.json
    remote_src: false
    force: true
########################################
- name: Change permission
  become: true
  command: >-
    chmod -R 777
    /home/{{user_var}}/mattermost/volumes/app/mattermost/config
  args:
    chdir: /home/{{user_var}}/mattermost/
########################################
- name: Modify docker-compose.without-nginx.yml to remove IP binding
  ansible.builtin.shell: |
    # Port HTTP (interface Web)
    sed -i "s/\${APP_PORT}:8065/{{ PORT }}:8065/" \
        /home/{{ user_var }}/mattermost/docker-compose.without-nginx.yml

    # Ports Mattermost Calls (UDP puis TCP)
    sed -i "s/\${CALLS_PORT}:\${CALLS_PORT}\/udp/{{ CALLS_PORT }}:{{ CALLS_PORT }}\/udp/" \
        /home/{{ user_var }}/mattermost/docker-compose.without-nginx.yml
    sed -i "s/\${CALLS_PORT}:\${CALLS_PORT}\/tcp/{{ CALLS_PORT }}:{{ CALLS_PORT }}\/tcp/" \
        /home/{{ user_var }}/mattermost/docker-compose.without-nginx.yml
  args:
    executable: /bin/bash      # garantit l’expansion correcte des variables
  tags:
    - modify_docker_compose
########################################

########################################
- name: fix ListenAddress to 8065
  replace:
    path: /home/{{ user_var }}/mattermost/volumes/app/mattermost/config/config.json
    regexp: '"ListenAddress": ":[0-9]+",'
    replace: '"ListenAddress": ":8065",'
########################################
- name: Change ownership of the directory
  become: true
  command: chown -R 2000:2000 ./volumes/app/mattermost
  args:
    chdir: /home/{{user_var}}/mattermost/
  tags:
    - change_owner
########################################
- name: Replace in .conf file
  replace:
    path: /home/{{user_var}}/mattermost/nginx/conf.d/default.conf
    regexp: 'server mattermost:8065;'
    replace: 'server mattermost:{{PORT}};'
########################################
- name: Replace in .env file
  replace:
    path: /home/{{user_var}}/mattermost/.env
    regexp: '^APP_PORT=.*'
    replace: 'APP_PORT={{PORT}}'
########################################
- name: Run docker-compose
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{user_var}}/mattermost
    files:
      - docker-compose.yml
      - docker-compose.without-nginx.yml
    state: present
