# .packer-ci.yml
---
stages:
  - packer-build

variables:
  IMAGE_NAME: "Janus"

build_image:
  stage: packer-build
  script:
    - cd services/packer
    - ls -la
    - packer build  packer.json
    - VERSION=$(vagrant cloud box show antitrust-ageless-custard-unreached/janus | grep -o 'Current Version:.*' | awk '{print $3}')
    - NEW_VERSION=$(awk -v version="$VERSION" 'BEGIN { printf "%.1f", version + 0.1 }')
    - vagrant cloud publish antitrust-ageless-custard-unreached/janus $NEW_VERSION virtualbox output-vagrant/package.box -d "janus box" --release --f

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
          - services/packer/scripts/setup.sh
      when: always
      allow_failure: true



