---
stages:
  - sast-build

scanner-sonarqube:
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_BEFORE_SHA !~ /0{40}/'  # this line checks that the commit is not empty, and is on main
      changes:
        - "**/{*[^.]md*,*.[^m]*,*.m,*.m[^d]*,*.md?*,*[^d]}" # this pattern looks to make sure a non-markdown file has changed
  stage: sast-build
  script:
    - rm -rf $CI_PROJECT_DIR/.scannerwork
    - mkdir -p $CI_PROJECT_DIR/.scannerwork

    # This command executes a Docker container based on the sonarsource/sonar-scanner-cli image.
    # It configures environment variables to specify the SonarQube server URL (SONAR_HOST_URL),
    # Sonar scanner options (SONAR_SCANNER_OPTS), and Sonar token (SONAR_TOKEN).
    # It also mounts the project directory in the container so that the Sonar scanner can analyze the source code.
    - docker run --rm -e SONAR_HOST_URL="$SERVER_IP" -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=$PROJECT_KEY" -e SONAR_TOKEN="$SONAR_TOKEN" -v "$CI_PROJECT_DIR:/usr/src" sonarsource/sonar-scanner-cli
