VAGRANT_CONFIG_VERSION = "2"
ANSIBLE_COMPATIBILITY_MODE = "2.13"
VM_NAME_VB = "supportInfra"
VM_HOSTNAME = "vagrant"
BOX_RAM_MB = "4096"
BOX_CPUS_COUNT = 4
STATIC_IP = "10.10.13.12"
PATH_TO_PASSWORD_VAULT = "user_group_vars/password_vault/password_vault.txt"
BOX_BASE = "antitrust-ageless-custard-unreached/janus"
JANUS_SUPPORT_INFRA_MEMORY = 2048
JANUS_SUPPORT_INFRA_CPUS = 1

# Function to provision services with Ansible
def provision_with_ansible(supportInfra, service)
  playbook_path = "/janus/domain/supportInfra/#{service}/#{service}.yml"
  supportInfra.vm.provision "ansible_local" do |ans|
    ans.compatibility_mode = "2.0"
    ans.playbook = playbook_path
    ans.inventory_path = "/janus/domain/supportInfra/inventory/inventory.ini"
    ans.verbose = "v"
    ans.vault_password_file = PATH_TO_PASSWORD_VAULT
  end
end

Vagrant.configure(VAGRANT_CONFIG_VERSION) do |config|
  config.vm.define VM_NAME_VB do |supportInfra|
    # Basic VM config
    supportInfra.vm.box = BOX_BASE
    supportInfra.vm.hostname = VM_HOSTNAME
    supportInfra.vm.post_up_message = File.read("post_up_message.txt")
    supportInfra.vm.network "private_network", ip: STATIC_IP

    janus_directory = File.expand_path("../..", Dir.pwd)
    supportInfra.vm.synced_folder janus_directory, "/janus",
      mount_options: ["dmode=775", "fmode=600"]

  # VirtualBox specific config
  supportInfra.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = VM_NAME_VB
    vb.memory = JANUS_SUPPORT_INFRA_MEMORY
    vb.cpus = JANUS_SUPPORT_INFRA_CPUS
  end

  supportInfra.vm.provision "ansible_local" do |ans|
    ans.compatibility_mode = "2.0"
    ans.inventory_path = "/janus/domain/supportInfra/inventory/inventory.ini"
    ans.playbook = "/janus/domain/supportInfra/common/common.yml"
    ans.verbose = "v"
  end 

  services_to_provision = ["reverseProxy"] 
  services_to_provision.each do |service|
    provision_with_ansible(supportInfra, service)
  end
end
end
  




