---
########################################
# All commands except those downgraded need sudo rights
########################################
- name: Configure Bitwarden
  hosts: 127.0.0.1 moleculeTest
  gather_facts: false
  become: true
  remote_user: "{{ user_var }}"
  connection: local
  ########################################
  # Import of all needed variable files
  ########################################
  vars_files:
    - ../user_group_vars/vault.yml
    - ../local_or_remote.yml
    - ../user_group_vars/usernames.yml
  ########################################
  # Answers for the installation script
  ########################################
  vars:
    answer_continue: y
    IP: 127.0.0.1
    https_port: "8444"
    http_port: "8089"
    use_lets_encrypt: n
    bitwarden_db_name: vaultinito
    installation_id: 7a0f8e27-2ed1-4c84-8f9a-b06100f97c8a
    installation_key: qMsz0vA28H5H7kUpOLhM
    bitwarden_url: https://func.bitwarden.com/api/dl/?app=self-host&platform=linux
    bitwarden_region: EU
    have_ssl_certificate: n
    generate_self_signed_ssl: y
    ########################################
    # Password for user bitwarden
    ########################################
    user_password_bitwarden: "{{ vault_user_password_bitwarden }}"
    ########################################
    # Config for the global.override.env file
    ########################################
    reply_to_email: Ild8NMJXewJewfZ7@gmx.fr
    smtp_host: mail.gmx.com
    smtp_port: 587
    smtp_ssl: false
    smtp_username: Ild8NMJXewJewfZ7@gmx.fr
    smtp_password: "{{ vault_smtp_password }}"
    disable_user_registration: false
    # hibp_api_key: TEST
    admin_settings_admins: marco.luyckx@ulb.be
    ########################################
    # "{{ username_admin_settings_admins }}" will provide access\
    # to the Admin Portal from that email address : https://127.0.0.1:8444/admin
    # The portal uses a secure means of passwordless authentication.
    # When users attempt to login, a secure link is sent to their email address.
    ########################################

    ########################################
    # Define the Backup directory
    # The extension is probably wrong
    ########################################
    backup_secure: bitwarden_backup_secure_infra.7z
    path_backup_secure: backup/secure/{{ backup_secure }}
    ########################################
    # Cyber Range
    # The extension is probably wrong
    ########################################
    cyber_range_active: "no"
    backup_cyber_range: bitwarden_backup_janus_cyber_range.7z
    path_backup_cyber_range: backup/cyber_range/{{ backup_cyber_range }}
    ########################################
    # Installation steps here :
    # https://bitwarden.com/help/install-on-premise-linux/
    ########################################
  tasks:
    - include_tasks: /janus/services/templates/bitwarden/bitwarden.yml
