---
# Generates /janus/domain/cyfun/identify/policies/output/legal_compliance.md

- name: Generate sector-aware legal compliance documentation
  hosts: user_domain
  gather_facts: false
  remote_user: "{{ user_var }}"
  connection: local

  vars_files:
    - ../../../../user/local_or_remote.yml

  vars:
    output_file: "/janus/domain/cyfun/identify/policies/output/legal_compliance.md"

  tasks:
    - name: Compute effective sector (default → accounting)
      set_fact:
        effective_sector: "{{ sector_type | default('accounting') }}"

    - name: Load sector-specific rules
      include_vars:
        file: "{{ playbook_dir }}/sectors/{{ effective_sector }}.yml"
        name: sector_rules

    - name: Build Markdown content
      set_fact:
        compliance_md: |
          # Legal and Regulatory Compliance

          {{ sector_rules.sector_rules.intro }}

          ## 1. Main Legal Rules

          {% for section in sector_rules.sector_rules.legal_sections %}
          ### {{ section.title }}

          {{ section.content }}

          {% endfor %}

          ## 2. Our Actions

          | Rule | How We Follow It | Who is Responsible |
          |------|------------------|-------------------|
          {% for action in sector_rules.sector_rules.actions_table %}
          | {{ action.rule }} | {{ action.how }} | {{ action.who }} |
          {% endfor %}

          ## 3. Review and Updates

          This document must be checked every year or when new rules appear. The **Directive Manager** handles updates. Changes are recorded below.

          ### Review History

          | Date | Reviewed By | Comment |
          |------|-------------|---------|
          {% for review in sector_rules.sector_rules.review_history %}
          | {{ review.date }} | {{ review.reviewed_by }} | {{ review.comment }} |
          {% endfor %}

          **Last Review**: {{ sector_rules.sector_rules.last_review }}
          
    - name: Write Markdown file
      copy:
        content: "{{ compliance_md }}"
        dest: "{{ output_file }}"
        mode: "0644"

    - name: Confirmation
      debug:
        msg: "✅ Markdown generated for sector '{{ effective_sector }}' at {{ output_file }}"
