---
########################################
# Import backup
########################################
- name: Create a backup directory
  file:
    path: /home/{{ user_var }}/invoiceninja/backup
    state: directory
    mode: "0777"
#########################################
- name: Save the backup import script on the VM
  template:
    src: ../../../services/backupScript/invoiceninja/import_backup.sh.j2
    dest: /home/{{ user_var }}/invoiceninja/backup/import_backup.sh
    mode: "0777"
#########################################
- name: Save the backup export script on the VM
  template:
    src: ../../../services/backupScript/invoiceninja/export_backup.sh.j2
    dest: /home/{{ user_var }}/invoiceninja/backup/export_backup.sh
    mode: "0777"
#######################################
- name: Copy the sql backup file to the VM
  copy:
    src: "{{ path_secure }}"
    dest: /home/{{ user_var }}/invoiceninja/backup/backup.sql
########################################
- name: Wait for 1 minute
  pause:
    seconds: 60
########################################
- name: Config CRON job to execute invoiceninja db
  become: true
  cron:
    name: invoiceninja_db_backup
    minute: "*"
    hour: "*"
    user: "{{ user_var }}"
    job: /home/{{ user_var }}/invoiceninja/backup/export_backup.sh
    cron_file: invoiceninja_db_backup
    state: present
#######################################
- name: Execute the backup command
  become: true
  ansible.builtin.shell: ./import_backup.sh
  args:
    chdir: /home/{{ user_var }}/invoiceninja/backup/
