---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox

platforms:
  - name: moleculeTest
    box: antitrust-ageless-custard-unreached/janus
    memory: 4096
    cpus: 2
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: "vagrant"
    provision: true
provisioner:
  name: ansible
verifier:
  name: ansible
