---
- name: Configure Jitsi
  hosts: 10.10.10.12 moleculeTest
  gather_facts: false
  connection: local
  remote_user: "{{user_var}}"

  vars_files:
    - ../local_or_remote.yml

  vars:
    IP: 127.0.0.1
    stable_version: stable-9220-1
    stable_version_dir: docker-jitsi-meet-stable-9220-1
    http_port: "8090"
    https_port: "8443"

    repo: https://github.com/jitsi/docker-jitsi-meet

  tasks:
    - include_tasks: /janus/services/templates/jitsi/jitsi.yml
