---
- name: Configure Codimd
  hosts: 10.10.10.12 moleculeTest
  gather_facts: false
  connection: local
  remote_user: "{{ user_var }}"

  vars_files:
    - ../user_group_vars/vault.yml
    - ../local_or_remote.yml

  vars:
    IP: 127.0.0.1
    # Postgres credentials
    postgres_db: "codimd"
    postgres_user: "codimd"
    # postgres_password TODO change it before production
    postgres_password: "{{ vault_postgres_password_codimd }}"
    # Accessibility
    db_url: "{{ postgres_password }}@database/{{ postgres_db }}"


  tasks:
    - include_tasks: /janus/services/templates/codimd/codimd.yml
