#!/bin/bash
###############################
#BRANCH NAME VERIFICATION   
###############################
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

#Define the regex pattern for branch naming convention
BRANCH_REGEX="^[A-Za-z0-9_-]+-[A-Za-z0-9_-]+-[A-Za-z0-9_-]+$"

#Check if the branch name matches the defined regex
if ! [[ $BRANCH_NAME =~ $BRANCH_REGEX ]]; then
   echo "Error: Invalid branch name format.
   Format is <Course>-<Last_name>-<task>"	
   exit 1
fi

###############################
#YAML SYNTHAX VERIFICATION   
###############################
YAML_FILES=$(git diff --cached --name-only --diff-filter=ACMRTUXB | grep '\.yml$')

for FILE in $YAML_FILES
do
   if ! yamllint -c .yamllint "$FILE"; then
      echo "Synthax error in $FILE. commit is canceled."
      exit 1
   fi
done

###############################
#BASH SCRIPT VERIFICATION   
###############################

SH_FILES=$(git diff --cached --name-only --diff-filter=ACMRTUXB | grep '\.sh$')

for FILE in $SH_FILES
do
   if ! shellcheck "$FILE"; then
      echo "Synthax error in $FILE. commit is canceled."
      exit 1
   fi
done

###############################
#VAGRANT_FILES VERIFICATION   
###############################
VAGRANT_FILES=$(git diff --cached --name-only --diff-filter=ACMRTUXB | grep 'Vagrantfile$')

for FILE in $VAGRANT_FILES
do
    #Vérification de la syntaxe Vagrantfile
   if ! vagrant validate "$FILE"; then
      echo "Synthax error in $FILE. commit is canceled."
      exit 1
   fi
done

exit 0